# Generated by Django 5.1.2 on 2025-04-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='./static/images')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('patronim', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=200, unique=True)),
                ('email', models.CharField(db_index=True, max_length=200, unique=True)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[(1, 'Мужской'), (2, 'Женский'), (3, 'Другое')], max_length=100)),
                ('citizenship', models.CharField(max_length=200)),
                ('education_level', models.CharField(choices=[(1, 'Среднее'), (2, 'Среднее специальное'), (3, 'Бакалавр')], max_length=100)),
                ('education_details', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('skills', models.TextField()),
                ('additional_info', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ('created',),
            },
        ),
    ]
