# Generated by Django 5.1.2 on 2025-04-22 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('min_age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Максимальный возраст')),
                ('min_education', models.CharField(choices=[(1, 'Среднее'), (2, 'Среднее профессиональное'), (3, 'Бакалавриат'), (4, 'Магистратура')], max_length=100, verbose_name='Минимальный уровень образования')),
                ('keywords', models.TextField(verbose_name='Ключевые слова (писать через запятую)')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterField(
            model_name='applyform',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='citizenship',
            field=models.CharField(max_length=200, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='education_details',
            field=models.TextField(blank=True, verbose_name='Образование(специальность)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='education_level',
            field=models.CharField(choices=[(1, 'Среднее'), (2, 'Среднее профессиональное'), (3, 'Бакалавриат'), (4, 'Магистратура')], max_length=100, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='email',
            field=models.EmailField(db_index=True, max_length=200, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='gender',
            field=models.CharField(choices=[(1, 'Мужской'), (2, 'Женский'), (3, 'Другой')], max_length=100, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='patronim',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='picture',
            field=models.ImageField(upload_to='./static/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='skills',
            field=models.TextField(verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
    ]
