# Generated by Django 5.1.2 on 2025-04-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_rename_applyform_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(choices=[('Среднее', 'Среднее'), ('Среднее профессиональное', 'Среднее профессиональное'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура')], max_length=100, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Другой', 'Другой')], max_length=100, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_education',
            field=models.CharField(choices=[('Среднее', 'Среднее'), ('Среднее профессиональное', 'Среднее профессиональное'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура')], max_length=100, verbose_name='Минимальный уровень образования'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.application')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.job')),
            ],
            options={
                'verbose_name': 'Анализ',
            },
        ),
    ]
