# Generated by Django 5.1.2 on 2025-04-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_application_education_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
